### ISSUE TITLE
I can not get the hir-tree

### ISSUE THREAD

**Issue by 3442853561** [rust-lang-nursery/rustc-guide#106]
When I:
```
cargo rustc -- -Zunpretty=hir-tree
```

I got:
```
error: unknown debugging option: `unpretty`
```

**Comment by pnkfelix** [comment]
It seems to work for me, e.g.:

```
% cargo clean
% cargo --version
cargo 1.26.0-nightly (311a5eda6 2018-03-26)
% rustc --version
rustc 1.26.0-nightly (e5277c145 2018-03-28)
% cargo rustc -- -Zunpretty=hir-tree
   Compiling hello v0.1.0 (file:///tmp/hello)
Crate {
    module: Mod {
        inner: Span {
            lo: BytePos(
                0
            ),
            hi: BytePos(
                13
            ),
            ctxt: #0
        },

[... elided ...]

    body_ids: [
        BodyId {
            node_id: NodeId(
                7
            )
        }
    ]
}    Finished dev [unoptimized + debuginfo] target(s) in 0.7 secs
```

What version of `cargo` and `rustc` are you seeing this on?

**Comment by 3442853561** [comment]
Thanks

**Comment by 3442853561** [comment]
And how can I let hir output in file

**Comment by pnkfelix** [comment]
> What version of cargo and rustc are you seeing this on?

**Comment by 3442853561** [comment]
@pnkfelix 
cargo 1.26.0-nightly

**Comment by mark-i-m** [comment]
Re: getting the output in a file. I imagine these easiest way is to just pipe it...

**Comment by pnkfelix** [comment]
@3442853561 do you have a commit number for your version of cargo? (See for example the transcript I put into [my comment above](https://github.com/rust-lang-nursery/rustc-guide/issues/106#issuecomment-377485316).)

**Comment by mark-i-m** [comment]
Ping @3442853561 Was this resolved?

**Comment by mark-i-m** [comment]
Going to close this to keep things tidy, but feel free to reopen!
