### ISSUE TITLE
Expand descriptions of the various compilation stages

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang-nursery/rustc-guide#115]
This is what we currently have: https://github.com/rust-lang-nursery/rustc-guide/blob/46864ca9714707f18e658afba9d2ea62afbe2374/src/how-to-build-and-run.md#running-xpy-and-building-a-stage1-compiler

There's a relevant thread on reddit about what these stages all mean and I think the descriptions in [this answer](https://www.reddit.com/r/rust/comments/8covpo/why_does_rustc_compile_itself_three_times_during/dxgnj6m/) could be incorporated into this section in the rustc guide

**Comment by ehsanmok** [comment]
I am interested in this as my very first PR. I'll prepare it over this weekend.

**Comment by mark-i-m** [comment]
Thanks @frewsxcv and @ehsanmok :)
