### ISSUE TITLE
there is some misunderstood parts

### ISSUE THREAD

**Issue by 3442853561** [rust-lang-nursery/rustc-guide#116]
In https://github.com/rust-lang-nursery/rustc-guide/blob/master/src/hir.md there is a sentence about "It is a desugared version of the abstract syntax tree"

I am not a native English speaker. So I just understand it in my mother language. When I tried to translate this sentence into Chinese which is my mother language. This looks like saying that HIR is a kind of abstract syntax tree.

If this sentence does not cause ambiguity in English, please close and ignore this issue.

**Comment by mark-i-m** [comment]
My understanding matches yours. The HIR is like an AST but with all the syntactic sugar removed.

**Comment by nagisa** [comment]
Definitely not all sugar is removed when lowering to HIR. What differs
between the two is the purpose - AST must faithfully represent code,
whereas HIR does not.

**Comment by mark-i-m** [comment]
@nagisa Thanks for the clarification :)

**Comment by Michael-F-Bryan** [comment]
> This looks like saying that HIR is a kind of abstract syntax tree.

From what I've gathered when trying to use the compiler internals, you could say a [`hir::Crate`] is a more compiler-friendly representation of the AST where we've changed the precise way things are stored and desugared some bits to make analysis easier.

[`hir::Crate`]: https://doc.rust-lang.org/nightly/nightly-rustc/rustc/hir/struct.Crate.html
