### ISSUE TITLE
Move the documentation related to ./x.py from https://forge.rust-lang.org 

### ISSUE THREAD

**Issue by rajcspsg** [rust-lang-nursery/rustc-guide#130]
As per discussion https://github.com/rust-lang-nursery/rustc-guide/issues/84#issuecomment-382978810 create a new documentation for `./x.py`. 

Copy the contents from link https://forge.rust-lang.org/x-py.html into the new file.

**Comment by mark-i-m** [comment]
It would be good to systematically move over relevant stuff from there. A PR on this repo should probably be accompanied by a PR on https://github.com/rust-lang-nursery/rust-forge

**Comment by mark-i-m** [comment]
@rajcspsg Did you want to work on this?

**Comment by rajcspsg** [comment]
@mark-i-m - my pleasure :) 
I've to copy the [x-py.md](https://github.com/rust-lang-nursery/rust-forge/blob/master/x-py.md) correct?

**Comment by mark-i-m** [comment]
I think that would be a great start. Some of the things on the forge page are already in the rustc-guide (https://rust-lang-nursery.github.io/rustc-guide/how-to-build-and-run.html), so we should try to avoid duplicating content.  I think we can add the content from the forge page to the existing chapter in the guide. (TBH, I haven't read the forge page, but let me know if you get stuck :) )

**Comment by mark-i-m** [comment]
Nice! I'll probably come around to this next week. Thanks :)

**Comment by rajcspsg** [comment]
@mark-i-m we can close this ticket correct?

**Comment by mark-i-m** [comment]
Yep! Thanks :)
