### ISSUE TITLE
Menu does not show up on Mobile

### ISSUE THREAD

**Issue by alexcameron89** [rust-lang-nursery/rustc-guide#138]
## Problem
When visiting the site on my phone, I cannot see the menu. This makes it hard to progress any further from the initial link to the guides.

I'm confused on what the problem is since building it locally shows the menu. I've compared the versions of MDBook locally and in CI, and they are the same.

If someone has an idea or some direction on how to fix this issue, I am happy to open a Pull Request.
## Screenshot:
![website](https://user-images.githubusercontent.com/5634381/40359221-89c0049c-5d87-11e8-8ebb-d65cf162d8c0.png)

## Local Build Screenshot:
![image](https://user-images.githubusercontent.com/5634381/40359358-134682c2-5d88-11e8-9394-19d8ad6a683f.png)

**Comment by ehuss** [comment]
My suspicion is that this is due to rust-lang-nursery/mdBook#697.

**Comment by mark-i-m** [comment]
I can confirm. I also noticed this with the [edition guide](https://github.com/rust-lang-nursery/edition-guide), so I think this is a problem with mdbook.

Perhaps @Michael-F-Bryan knows?

**Comment by 0xAC44** [comment]
As a temporary workaround, I'm able to open the menu by tapping where it's supposed to be, even though it's invisible.
