### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by sunjay** [rust-lang-nursery/rustc-guide#144]
The URL: https://rust-lang-nursery.github.io/rustc-guide/

Produces:
![image](https://user-images.githubusercontent.com/530939/40449844-aee2bb04-5e8e-11e8-9a3c-34eb45a39f06.png)

Maybe someone changed something in the settings of the repo? I would check, but I don't have access.

**Comment by mark-i-m** [comment]
Hmm... that might have been me. I fat-fingered the delete-branch button earlier and restored the branch, but maybe github didn't catch on? (It's a good thing the `master` branch is protected!)

**Comment by mark-i-m** [comment]
I just pushed a dummy commit to the gh-pages branch in hopes of spurring github to rerender...

**Comment by mark-i-m** [comment]
@nikomatsakis Could you confirm that the GH pages is still enabled?

**Comment by sunjay** [comment]
You may have to reconfigure it in the settings if the branch was deleted.

**Comment by mark-i-m** [comment]
Oh, :disappointed: 

I don't have permissions to fiddle with settings...

**Comment by sunjay** [comment]
@nikomatsakis confirmed that the right branch is enabled, but it appears to be stuck building the site. I'm going to contact support.

**Comment by mark-i-m** [comment]
Thanks for investigating @sunjay

**Comment by sunjay** [comment]
I contacted Github support and the site is back up! Here's their reply:

> Hi Sunjay,
> 
> We require that an admin of the repo create the initial Pages build. It looks like all the pushes on this repo to the gh-pages branch have happened from users that are not an admin or owner.
>
> I went ahead and triggered a build for you manually, but going forward have the owner of the repo create a commit in new repos and the site will build automatically.
>
> Now that the site has been built once, future pushes will automatically trigger a rebuild regardless of which user pushes the changes.
>
> Hope this helps! Let us know if you need anything else.

So hopefully that clears up what happened.

**Comment by mark-i-m** [comment]
Thanks @sunjay !
