### ISSUE TITLE
Sidebar subsection titles are cut-off

### ISSUE THREAD

**Issue by sunjay** [rust-lang-nursery/rustc-guide#172]
![image](https://user-images.githubusercontent.com/530939/42903381-84e14af4-8a86-11e8-9a46-1c62c1ff0324.png)

This screenshot shows 17.1.2 and 17.3.1, but there are several more subsection titles that are cut-off in the sidebar.

**Comment by mark-i-m** [comment]
Can confirm. It was not doing this before. I will shorten the names.

**Comment by sunjay** [comment]
Maybe the CSS could be adjusted to let long titles wrap to the next one? I think the second chapter title already does that. It just doesn't work in the subsections. That might be a better solution for different screen sizes too.

**Comment by mark-i-m** [comment]
Hmm... I think this is more of an mdbook issue. The chapter list is generated automatically from `SUMMARY.md`.

I opened https://github.com/rust-lang-nursery/mdBook/issues/729

**Comment by mark-i-m** [comment]
It looks like this is fixed in https://github.com/rust-lang-nursery/mdBook/pull/732... I will keep this in until mdbook 0.1.9 is out.
