### ISSUE TITLE
Clarify that `'static` is only a "free" lifetime parameter because of coercion

### ISSUE THREAD

**Issue by alexreg** [rust-lang-nursery/rustc-guide#185]
See [this section](https://rust-lang-nursery.github.io/rustc-guide/traits/canonicalization.html#canonicalizing-the-query), which is otherwise confusing.

This is my understanding, at least; someone correct me if I'm wrong.

**Comment by nikomatsakis** [comment]
I don't know what you mean. I think `'static` is "free" because it is bound outside of the whole program. I'm not sure what coercion has to do with it?

**Comment by alexreg** [comment]
Okay... I would consider the binding to be within the program still (but around everything the user writes). It should be clarified either way though.

**Comment by mark-i-m** [comment]
I think the main point is that it is free wrt that particular query (because it is not bound within the query). I'm still not quite understanding where the confusion is coming from. What would you suggest as a fix?

**Comment by alexreg** [comment]
It's certainly *not* free with that particular query if the binding scope is the whole program.

**Comment by alexreg** [comment]
@mark-i-m A variable is "bound" if it is captured by any parent quantifier.

**Comment by mark-i-m** [comment]
Yes, but only in the context of the binding.

Foo<T> has a free T, whereas impl<T> Foo<T> has a bound T.

**Comment by alexreg** [comment]
Well, if the binding is around the program, then it definitely is it in the context of the binding! Either way, I think this is very confusing, and worth removing the "free" at the very least (if not saying "bound").

**Comment by alexreg** [comment]
It's not right to call it free though, either way. The logician in me baulks at it!

**Comment by nikomatsakis** [comment]
I still think free is the appropriate term and I don't really understand the objection, to be honest. I'm not sure how important this distinction is though.

**Comment by alexreg** [comment]
@nikomatsakis Okay, well I reread now, and I think I see where my confusion is coming from (and I think others may be pretty confused too). This is mainly that the `'static` lifetime is quantified around the whole program, thus it is bound to the same lifetime everywhere... this goes against the intuitive notion of "free", even if it is indeed technically correct. Just worth a clarification I think, like @mark-i-m says.
