### ISSUE TITLE
/home/user/.zshenv:5: command not found: rustc

### ISSUE THREAD

**Issue by tuyenpm9** [rust-lang-nursery/rustc-guide#194]
Error as title: `/home/sugar/.zshenv:5: command not found: rustc`

I installed rust with `modify path: y` and checked with print `$path` and observed `/home/user/.cargo/bin` in first elemnt of `$path` array. So I have no clue why `rustc` is not found. Also tried to `add .cargo/bin` in `.zshrc` instead of `.zshenv` but also didn't work.

**Comment by tuyenpm9** [comment]
I asked in unix.stackexchange.com: `https://unix.stackexchange.com/q/466685/256195` and at the end even `modify path` is `yes` we still have to put `~./cargo/bin` in `path` in front of `RUST_SRC_PATH=$(rustc --print sysroot)/lib/rustlib/src/rust/src/` in `.zshenv`.

Note even `RUST_SRC_PATH` in `.zshrc` still error so maybe modify path at the begining of `.zshrc` or end of `.zshenv` is good idea.

**Comment by mark-i-m** [comment]
Good to know. Thanks :)
