### ISSUE TITLE
Can't find "use-jemalloc" in config.toml.

### ISSUE THREAD

**Issue by kenta7777** [rust-lang-nursery/rustc-guide#227]
[how-to-build-and-run.md](https://github.com/rust-lang-nursery/rustc-guide/blob/607a58f8d2f56068ac1cf60c550d54f3ee6d90c6/src/how-to-build-and-run.md) tells us to open up to config.toml file and change the following settings.
`use-jemalloc = false`
However, the statement cannot be found in the file.

**Comment by ehuss** [comment]
This was changed just a day ago to `jemalloc` in rust-lang/rust#55238.

**Comment by kenta7777** [comment]
@ehuss Thank you for your comment. Then, should I send a PR for this revision?

**Comment by mark-i-m** [comment]
That would be great!

**Comment by kenta7777** [comment]
@mark-i-m I'll send a PR.

**Comment by kenta7777** [comment]
Thanks!
