### ISSUE TITLE
What are "filemaps"?

### ISSUE THREAD

**Issue by alexreg** [rust-lang-nursery/rustc-guide#35]
They're mentioned on <https://rust-lang-nursery.github.io/rustc-guide/the-parser.html>, but not defined. I think it would be good to explain what they are first.

**Comment by mark-i-m** [comment]
cc #13

**Comment by Michael-F-Bryan** [comment]
Does anyone mind if I have a go at answering this one?

**Comment by mark-i-m** [comment]
Ping @Michael-F-Bryan 

Any updates?

**Comment by Michael-F-Bryan** [comment]
Sorry @mark-i-m, I've had a lot on my plate and didn't get around to this. Over the weekend I was wanting to play around with rustc internals to create a tool similar to `cbindgen` so I imagine that'll give me a chance to document things and add a paragraph or two on filemaps/codemaps.

**Comment by mark-i-m** [comment]
@Michael-F-Bryan Thanks for the update :)

**Comment by mark-i-m** [comment]
@Michael-F-Bryan Ping

(sorry to bug you again)
