### ISSUE TITLE
Line wrap convention?

### ISSUE THREAD

**Issue by alexreg** [rust-lang-nursery/rustc-guide#42]
What's the line wrap convention? I initially guessed 80 chars max, but then it seems like a) a few lines overflow (I'd guess these were oversights), b) many lines wrap before they need to (I'd guess intentionally). I can't figure out the logic for b) in particular, since no consistent scheme seems to be used.

Personally, I'm not a big fan of hard wrapping in markup files (or code, to a lesser extent, though I know that's more contentious!). Should we be doing wrapping at all? If yes, let's document a consistent style, I say.

**Comment by mark-i-m** [comment]
I don't think there is a hard style guide... I personally prefer hard wrapping at 80chars. If this was code, I would say "use `rustfmt`", but I have no strong preference for markup files.

Feel free to pick a convention. If you do, please add a note in the README. This could be turned a tracking issue of files that need to be properly formatted.

Let me know what you think :)

**Comment by alexreg** [comment]
Hard-wrapping at 80, and keeping formatted parts (backticks, bold, underline) on their own line seems to make the most sense to me. Is there a tool that can automatically do this?

**Comment by mark-i-m** [comment]
> Is there a tool that can automatically do this?

Unfortunately, I don't know. I usually just use vim (`gqgq`)...

**Comment by petrochenkov** [comment]
100 characters is the limit currently enforced by tidy.
Everything below that is either personal preferences or rustfmt's preferences.

**Comment by petrochenkov** [comment]
Oh wait, do you mean for this repo?

**Comment by mark-i-m** [comment]
> Oh wait, do you mean for this repo?

Yep, since it is mostly markdown rustfmt doesn't help :'(

On Feb 5, 2018 1:21 AM, "Vadim Petrochenkov" <notifications@github.com>
wrote:

Oh wait, do you mean for this repo?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/rust-lang-nursery/rustc-guide/issues/42#issuecomment-363000777>,
or mute the thread

**Comment by alexreg** [comment]
Hmm, we may be able to use the GNU `fmt` utility for this, and integrate it into the build script?

**Comment by mark-i-m** [comment]
I'm not familiar with `fmt`, but it sounds promising. I think the best thing would be to have some sort of `tidy` check that is run by travis. That way a PR gets blocked until formatting is fixed.

**Comment by alexreg** [comment]
Yeah, that could work too. Should be pretty easy to write a Bash script that does that.

**Comment by nikomatsakis** [comment]
I'm generally in favor of line wrapping -- it makes the text much more readable when it's not rendered, and it can help make diffs more readable  -- though I see the advantage of not doing it too. I don't know about tooling for doing it; I also just hit M-q in emacs to do it. I suppose fmt might work?

**Comment by alexreg** [comment]
I've seen some odd line wrapping conventions around the Rust codebase (70 chars?!), and even though I prefer not line wrapping, it seems like most people like it... so as long as we could standardise it, and put a check on the CI, that could work. (I just tried `fmt -w 80` here, which works nicely for Markdown.

**Comment by mark-i-m** [comment]
Thanks for the investigation @alexreg :)

Would you mind make a PR to add such a check to the CI?

**Comment by alexreg** [comment]
@mark-i-m Sure, that should be simple enough...
