### ISSUE TITLE
CI using old cache of mdbook

### ISSUE THREAD

**Issue by ehuss** [rust-lang-nursery/rustc-guide#58]
I'm not 100% certain without access to the Travis cache, but I believe that it is using an old version of mdbook (0.0.28) from the cache.  This was noticed because Travis is not running mdbook-linkcheck, and the output in the Travis logs looks like the old version.

In the Travis logs, it looks like PRs are picking up this old cache from the master branch:
```
fetching master/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--cargo-stable.tgz
found cache
```

Due to the way [ci/install.sh](https://github.com/rust-lang-nursery/rustc-guide/blob/master/ci/install.sh) is written, it will skip if mdbook is already installed, but it does not check which version is already installed.

A quick short-term solution is to delete the travis caches.

I can make a PR to change the install.sh script to force a reinstall if there is a version mismatch.  Alternatively, you can just manually delete the travis caches whenever you upgrade mdbook.

**Comment by mark-i-m** [comment]
> I can make a PR to change the install.sh script to force a reinstall if there is a version mismatch.

Thanks @ehuss ! I would appreciate that :)

It explains https://github.com/rust-lang-nursery/rustc-guide/pull/47#discussion_r166657423

**Comment by mark-i-m** [comment]
I just dropped the caches, and will restart the travis builds for outstanding PRs, but a permanent fix would be good.
