### ISSUE TITLE
How to use CTAGS

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/rustc-guide#80]
One of the challenges with rustc is that the RLS can't handle it, making code navigation difficult. I personally use ctags; I use this script to set it up:

https://github.com/nikomatsakis/rust-etags

CTAGS integrate into emacs + vim quite easily, I don't know about other editors. I typically have this common as my standard "build rustc" command:

```
rust-ctags src/lib* && ./x.py build ...
```

This allows me to do "jump-to-def" with whatever functions were around when I last built .This is ridiculously useful. 

Some setup instructions should be added to the "getting started" chapter I think.

**Comment by mark-i-m** [comment]
I have actually always wanted better ctags support for rust... I once tried to write such a utility from scratch, but it turns out to be a bit hard without something like `libsyntax 2.0`.

**Comment by nikomatsakis** [comment]
Yes... the current one is "decent enough" but definitely limited. I've contemplated making it work via rustc output (or save analysis or something) but usually before getting started I realize I should do something else.
