### ISSUE TITLE
deployment stopped working

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/rustc-guide#82]
I don't really know why but [travis is failing](https://travis-ci.org/rust-lang-nursery/rustc-guide/jobs/351677551#L548), giving a kind of generic message:

> Couldn't push the build to github.com/rust-lang-nursery/rustc-guide.git:gh-pages

Bah humbug. I hate this stuff. Anybody got a clue? I can give permissions as needed if think you know how to fix =)

**Comment by ehuss** [comment]
Travis released a new version of their deployment tool (dpl) and it broke a lot of repositories.  One of the Travis employees has a workaround (see travis-ci/travis-ci#9312).  I would suspect they will roll out a fix very soon.

**Comment by mark-i-m** [comment]
It looks like it's working again.
