### ISSUE TITLE
./x.py check

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/rustc-guide#84]
So I've recently discovered that `./x.py check` is actually *really dang fast* -- we should add a note about it in the "how to build compiler" section. It's in particular very useful when you're doing some kind of "type-based refactoring", like renaming a method, or changing the signature of some function.

**Comment by rajcspsg** [comment]
@nikomatsakis @mark-i-m - can I take this easy issue?

**Comment by mark-i-m** [comment]
Go for it :)

**Comment by rajcspsg** [comment]
@nikomatsakis - I've updated the [this](https://github.com/rust-lang-nursery/rustc-guide/blob/master/src/how-to-build-and-run.md) file correct?
Also, I see the document has already something related to `x.py` build command for rustc.

**Comment by rajcspsg** [comment]
@nikomatsakis @mark-i-m - I see documentation related to https://forge.rust-lang.org/x-py.html.
Do I've to move the contents here as mentioned in this [issue 98](https://github.com/rust-lang-nursery/rustc-guide/issues/98)?

**Comment by mark-i-m** [comment]
> I've updated the this file correct?
Also, I see the document has already something related to x.py build command for rustc.

Yep, that's the right file. It already had content on some of the other x.py commands, but not for `check`.

> I see documentation related to https://forge.rust-lang.org/x-py.html.
Do I've to move the contents here as mentioned in this issue 98?

Hmm... I think it would be good to do, but not in this PR. I also think it is distinct from #98... Could you open a new issue for it?

**Comment by mark-i-m** [comment]
Ping @rajcspsg Any updates?

**Comment by rajcspsg** [comment]
@mark-i-m Sorry for delay. I didn't noticed when you 👍 my comment.
I've created PR for this issue https://github.com/rust-lang-nursery/rustc-guide/pull/129.

**Comment by mark-i-m** [comment]
@rajcspsg Thanks!
